### ISSUE TITLE
请问mGLSurfaceView如何正确设置全屏显示？

### ISSUE THREAD

**Issue by heweiquan** [gqjjqg/android-extend#11]
[项目demo](https://github.com/heweiquan/arcface_demo)，由[asdfqwrasdf/ArcFaceDemo](https://github.com/asdfqwrasdf/ArcFaceDemo)修改过来的，其中项目中使用到楼主的库，但是默认只能按屏幕宽高比来显示，于是就有黑边存在，如下如所示：
![default](https://user-images.githubusercontent.com/13057762/42070897-16fa3f32-7b8b-11e8-8482-a36a1ff1999a.png)
通过网络搜索找到的设置全屏的方法：将开源库中的CameraSurfaceView进行修改：
![default](https://user-images.githubusercontent.com/13057762/42070700-4c5c7c90-7b8a-11e8-8a73-ecf4d6cbd10f.png)
但是出现了人像拉伸的问题，这个问题如何解决？
![default](https://user-images.githubusercontent.com/13057762/42070917-23c3e8ee-7b8b-11e8-975a-847c7243b8f7.png)

**Comment by gqjjqg** [comment]
1. mGLSurfaceView 是按照相机的preview 宽高比设置的
2. 屏幕的宽高比和相机的preview宽高比必定存在不一致的情况
3. 需要全屏显示并且没有拉伸挤压，则必须要对preview做裁剪按屏幕比例显示
简单的办法，直接裁剪preview图像使得图像尺寸和屏幕一致
复杂一点，自己修改渲染代码等做crop显示
