### ISSUE TITLE
竖屏模式下，将手机横放，绿框获取的位置相反了。

### ISSUE THREAD

**Issue by Jibinghao** [gqjjqg/android-extend#21]

**Comment by Jibinghao** [comment]
前置摄像头才会这样 后置摄像头不会

**Comment by Jibinghao** [comment]
https://github.com/asdfqwrasdf/ArcFaceDemo
操作步骤 先开后摄像头识别 然后点击那个“旋转”按钮，切换到前摄像头就会出现这样子，如果直接是从前摄像头进去就不会。

**Comment by gqjjqg** [comment]
已修复  e0d4252d8b512dbb87d8fad784e52ee54fe22b95
