### ISSUE TITLE
修改框的样式

### ISSUE THREAD

**Issue by AndroidAndYang** [gqjjqg/android-extend#23]
大神你好，我想修改GLES2Render类中的draw_rect中的native方法，需求是画那种像扫描的框，只有四个角的那种，而不是一个正方形。请问我改如何修改？往指教，谢谢。

**Comment by gqjjqg** [comment]
可以GL绘制纹理，具体需要自己实现。
简单处理可以直接surfaceview绘制。

**Comment by AndroidAndYang** [comment]
在CameraSurfaceView中的onAfterRender方法获取到的rect，我有看到在jni里面你是有计算处理的，如果我直接在onAfterRender绘制，坐标我该怎么计算？

**Comment by gqjjqg** [comment]
onAfterRender 绘制 需要根据View的大小和Image的大小，计算一个比例来缩放rect，再把rect 基于Image的坐标旋转到基于View的坐标上即可。

**Comment by AndroidAndYang** [comment]
谢谢
