### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gxh-apologize** [gqjjqg/android-extend#25]
您好，我使用的是GLSurfaceView，参考了sample，但是报错如下，请问是什么原因呢？
usb摄像头，安卓7.1，商米收银机设备，申请了Camera权限。

01-08 17:39:40.277 21476-21476/cn.shundao.cashiersystem I/ATC.: image.so JNI_OnLoad
01-08 17:39:40.297 21476-21476/cn.shundao.cashiersystem W/o.cashiersystem: type=1400 audit(0.0:4121): avc: denied { getattr } for path="/dev/video0" dev="tmpfs" ino=538924 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:video_device:s0 tclass=chr_file permissive=0
01-08 17:39:40.313 21476-21476/cn.shundao.cashiersystem I/ATC.: video.so JNI_OnLoad
01-08 17:39:40.313 21476-21476/cn.shundao.cashiersystem E/ATC.: Cannot identify '/dev/video0': 13, Permission denied
    Open_Video = -2
01-08 17:39:40.337 21476-21513/cn.shundao.cashiersystem A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xf in tid 21513 (Thread-5)

**Comment by gqjjqg** [comment]
走UVC接口使用时的有两种方式：
1. 系统自己可以自己挂载为相机时，直接调用系统相机API。
2. 系统不能自己挂载，需要先确认是否支持V4L2, 如是，要确定UVC相机的设备号是否是 /dev/video0 ，如是，需要确保有访问权限。对于权限问题，可能需要编译APK成系统的APK，或者取得ROOT权限。

从log上看，是访问权限不足：
Cannot identify '/dev/video0': 13, Permission denied
Open_Video = -2
