### ISSUE TITLE
oppo 手机会报此问题

### ISSUE THREAD

**Issue by kulong51** [gqjjqg/android-extend#26]
java.lang.ArrayIndexOutOfBoundsException
src.length=1382400 srcPos=0 dst.length=3110400 dstPos=0 length=3110400
1 java.lang.System.arraycopy(Native Method)
2 com.guo.android_extend.widget.CameraSurfaceView.onPreviewFrame(CameraSurfaceView.java:225)
3 android.hardware.Camera$EventHandler.handleMessage(Camera.java:1350)
4 android.os.Handler.dispatchMessage(Handler.java:110)
5 android.os.Looper.loop(Looper.java:232)
6 android.app.ActivityThread.main(ActivityThread.java:6910)
7 java.lang.reflect.Method.invoke(Native Method)
8 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103)
9 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

**Comment by gqjjqg** [comment]
看上去是改变了分辨率？请提供更多的信息来定位。
