### ISSUE TITLE
CameraGLSurfaceView 用作相机预览时无法全屏，不知能解决吗？

### ISSUE THREAD

**Issue by synchroni** [gqjjqg/android-extend#3]
CameraGLSurfaceView 用作相机预览时无法全屏，不知能解决吗？ 它里面有做有操作，怎么给Camera.setPreviewSize  都没用。。。

**Comment by gqjjqg** [comment]
CameraGLSurfaceView 和 android 自带的渲染过程是分离的,另外独立实现了用opengl在c层做渲染的
所以设置 Camera.setPreviewSize 无效.
这个类用来作camera 的preview显示, 实现上主要考虑和 camera 的preview size等比例,
想要撑满整个父布局,需要布局尺寸比例和camera 的preview size 比例一致.

**Comment by gqjjqg** [comment]
```C++
@Override
	public boolean startPreviewLater() {
		// TODO Auto-generated method stub
		mGLSurfaceView.setAspectRatio(0.0);
		return false;
	}
```
以上是 临时的解决办法

**Comment by synchroni** [comment]
谢谢。
