### ISSUE TITLE
使用CameraGLSurfaceView的内存问题

### ISSUE THREAD

**Issue by yawin** [gqjjqg/android-extend#5]
HI，我在使用CameraGLSurfaceView 采集preview 数据然后用于做人脸识别开发，同时使用mGLSurfaceView.getGLES2Render().draw_rect() 绘制识别到的人脸矩形，我使用5.0的设备运行程序，一直处于预览捕捉人脸阶段：
1. 应用占用内存没有变化；
2. 系统可使用内存一直减少，直至最后程序crash。
能问下这个是没有适配的问题吗？

**Comment by gqjjqg** [comment]
请提供详细log，应该和适配没有关系。
建议先调查哪里内存泄漏

**Comment by yawin** [comment]
请问下有没有其他什么方法可以输出日志，因为设备无法调试，需要把日志写到文件里？

**Comment by yawin** [comment]
使用你提供的demo  CameraActivity，在我手机上运行，发现系统剩余内存一直往下降，日志没有什么特别的，就是这些：
12-25 20:12:57.651 29179-29179/com.guo.samples E/FrameHelper: FPS = 9
12-25 20:12:58.735 29179-29179/com.guo.samples E/FrameHelper: FPS = 10
12-25 20:12:59.833 29179-29179/com.guo.samples E/FrameHelper: FPS = 10
12-25 20:13:00.931 29179-29179/com.guo.samples E/FrameHelper: FPS = 10
12-25 20:13:02.041 29179-29179/com.guo.samples E/FrameHelper: FPS = 9
12-25 20:13:03.138 29179-29179/com.guo.samples E/FrameHelper: FPS = 9
12-25 20:13:04.238 29179-29179/com.guo.samples E/FrameHelper: FPS = 10
12-25 20:13:05.337 29179-29179/com.guo.samples E/FrameHelper: FPS = 10
12-25 20:13:06.434 29179-29179/com.guo.samples E/FrameHelper: FPS = 10
12-25 20:13:07.537 29179-29179/com.guo.samples E/FrameHelper: FPS = 9
12-25 20:13:08.631 29179-29179/com.guo.samples E/FrameHelper: FPS = 10
12-25 20:13:09.731 29179-29179/com.guo.samples E/FrameHelper: FPS = 10
12-25 20:13:10.830 29179-29179/com.guo.samples E/FrameHelper: FPS = 10

**Comment by yawin** [comment]
打印内存使用情况代码：
StringBuilder sb = new StringBuilder();
				final ActivityManager activityManager = (ActivityManager) CameraActivity.this.getSystemService(Context.ACTIVITY_SERVICE);
				ActivityManager.MemoryInfo info = new ActivityManager.MemoryInfo();
				activityManager.getMemoryInfo(info);
				sb.append("系统剩余内存:").append(info.availMem >> 20).append("M\n");
				sb.append("应用总内存:").append(Runtime.getRuntime().totalMemory() >> 20).append("M\n");
				sb.append("应用最大内存:").append(Runtime.getRuntime().maxMemory() >> 20).append("M\n");
				sb.append("应用剩余内存:").append(Runtime.getRuntime().freeMemory() >> 20).append("M\n");
				if (memory.getText().length() > 140) {
					memory.setText(sb.toString());
				} else {
					memory.append(sb.toString());
				}

**Comment by gqjjqg** [comment]
如果确定是CameraGLSurfaceView 内存泄漏或者是别的控件有泄漏，请提供详细LOG。
使用logcat > file 命令即可保存到文件。

**Comment by yawin** [comment]
请问下是否在你自己的测试机上运行你的demo 没有问题？我手机重启后就只打开了你的demo，点击camera项，打开预览界面，然后放着不动，然后就会发现系统可用内存一直减少，只有重启手机才会恢复。

**Comment by yawin** [comment]
你说的详细日志请问下去哪看，我用ddms 查看没有什么日志输出。。

**Comment by asdfqwrasdf** [comment]
是samples的工程吗？

**Comment by gqjjqg** [comment]
是samples工程吗？

**Comment by gqjjqg** [comment]
我这边已经自己测试过设备，运行1小时多次触发GC之后没有发现有泄露现象。

**Comment by yawin** [comment]
希望你能看下系统可用内存状态，而不是看应用内存，应用内存是没变化，但是系统可用内存被一直消耗，我在1.5G 内存设备上运行一晚上就死了

**Comment by gqjjqg** [comment]
我直接用AS的profiler监视内存情况，如果应用本身没有泄露，那系统可用内存却一直消耗，建议调查是否有别的app泄露或者系统GC异常了。
