### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by heweiquan** [gqjjqg/android-extend#8]
1. 使用implementation 'com.guo.android_extend:android-extend:1.0.1'引入代码正常使用，但是FrameHelper一直打印FPS，我项目中的其他log都看不到了，于是我尝试克隆源码导入项目，但是出现下面2的问题

![image](https://user-images.githubusercontent.com/13057762/37748846-4920c6f2-2dc0-11e8-9319-54dc8d4d11e7.png)

2. 克隆源码，引入android-extend，运行程序suraceview一片漆黑，然后点击屏幕居然还秒退了

![image](https://user-images.githubusercontent.com/13057762/37748568-3d1ed958-2dbf-11e8-8784-2b7394275da3.png)

![image](https://user-images.githubusercontent.com/13057762/37748607-646cc218-2dbf-11e8-8600-120543d81c91.png)

发现CameraSurfaceView.OnCameraListener中的startPreviewLater()被startPreviewImmediately()替换了，这有啥不同？

秒退的日志：
![image](https://user-images.githubusercontent.com/13057762/37748767-0ac52524-2dc0-11e8-95f0-ed8857aab0fb.png)

**Comment by gqjjqg** [comment]
FrameHelper 这个关闭就好了
