### ISSUE TITLE
Camare2的OnDrawListener回调接口

### ISSUE THREAD

**Issue by ulike** [gqjjqg/android-extend#9]
Camera的CameraSurfaceView.OnCameraListener里面的onPreview会返回结果给onAfterRender里面使用，比如人脸检测结果给render渲染，Camare2的OnDrawListener回调接口onDrawOverlap方法里面怎么得到onPreview里面的结果呢？

**Comment by gqjjqg** [comment]
提交了更新，保持和camera1回调一致
